### ISSUE TITLE
Platform: TURIBIKE

### ISSUE THREAD

**Issue by fro-profesional** [clau-org/.project-clau#5]
# Turibike by Clau
## Descripción
Sistema de reservas de horarios, pagos por internet, pagina de información y con un solo tipo de usuario administrador y usuarios "efimeros" o "transaccionales" a travez del correo electronico. 

## Modelos
- Usuarios
- Eventos
- Ventas

## Provedores
- AWS
- Cloudfare
- Koyeb
- Pusher

## Product

**Admin**
- [ ] El Sistema debe de contar con una cuenta Default Admin
- [ ] Como Administrador puedo registrar mas usuarios Admin
- [ ] Como Administrador puedo Visualizar, Crear, Editar y Suspender Eventos
- [ ] Como Administrador puedo Visualizar, Crear Ventas

**Cliente**
- [ ] Como cliente puedo visualizar el Home del sitio web (Redes sociales, eslogan, etc...)
- [ ] Como cliente puedo ver el catalogo de Eventos
- [ ] Como cliente puedo comprar/reservar con mi email (El sistema contempla que dos usuarios no pueda comprar el mismo lugar)

**Modelos**
**Usuarios:** 
- Nombre
- Email
- Edad
- Genero
- Referal code

**Eventos**
- Titulo
- Descripción
- Imágenes
- Calendario (Arreglo con las siguientes propiedades)
    - Dia 
    - Precio (Si el precio siempre es el mismo podemos moverlo a un atributo del evento no del el día del evento)
    - lugares

**Ventas**
- Evento
- Usuario

**Pagina**
- Home page con video
- Usuario

**Revisar**
- Escanear boletos o eventos con QR *
- Provedor correos
- https://next.vuetifyjs.com/en/getting-started/installation/

**Comment by fro-profesional** [comment]
Simple event reservation by stages like:
- seats
- users
- confirmation
- payment

Also hold seats by ~10min so the seats wont be taken

**Comment by DanCuatro** [comment]
https://docs.google.com/spreadsheets/d/1eE8zcmBR9KxOhhsi2kJ8CGl7Z0I49aiF_i0-8hrbTA4/edit?usp=sharing

**Comment by fro-profesional** [comment]
## Cloud provider

- AWS
- Cloudfare 
- Koyeb

**Comment by fro-profesional** [comment]
Se necesita el dominio

**Comment by fro-profesional** [comment]
# Turibike by Clau
## Descripción
Sistema de reservas de horarios, pagos por internet, pagina de información y con un solo tipo de usuario administrador y usuarios "efimeros" o "transaccionales" a travez del correo electronico. 

## Modelos
- Usuarios
- Eventos
- Ventas

## Provedores
- AWS
- Cloudfare
- Koyeb
- Pusher

## Product

**Admin**
- [ ] El Sistema debe de contar con una cuenta Default Admin
- [ ] Como Administrador puedo registrar mas usuarios Admin
- [ ] Como Administrador puedo Visualizar, Crear, Editar y Suspender Eventos
- [ ] Como Administrador puedo Visualizar, Crear Ventas

**Cliente**
- [ ] Como cliente puedo visualizar el Home del sitio web (Redes sociales, eslogan, etc...)
- [ ] Como cliente puedo ver el catalogo de Eventos
- [ ] Como cliente puedo comprar/reservar con mi email (El sistema contempla que dos usuarios no pueda comprar el mismo lugar)

**Modelos**
**Usuarios:** 
- Nombre
- Email
- Edad
- Genero
- Referal code

**Eventos**
- Titulo
- Descripción
- Imágenes
- Calendario (Arreglo con las siguientes propiedades)
    - Dia 
    - Precio (Si el precio siempre es el mismo podemos moverlo a un atributo del evento no del el día del evento)
    - lugares

**Ventas**
- Evento
- Usuario

**Pagina**
- Home page con video
- Usuario

**Revisar**
- Escanear boletos o eventos con QR *
- Provedor correos
- https://next.vuetifyjs.com/en/getting-started/installation/

**Comment by fro-profesional** [comment]
[Turibike.pdf](https://github.com/clau-org/.project-clau/files/10387004/Turibike.pdf)
